### ISSUE TITLE
Running npx nx run cms-api:build [Failing]

### ISSUE THREAD

**Issue by K-K-Kola** [tshegomotlatle/cms#9]
Build process for the API is failing.

Possible culprit might be Prisma connection [lack of credentials perhaps to repo].

Also, how should the application behave if credentials don't exist yet if that's the case.

-------------------

![Screenshot 2024-07-15 155332](https://github.com/user-attachments/assets/26702b99-7d40-4acb-bee9-410922202028)
![Screenshot 2024-07-15 155423](https://github.com/user-attachments/assets/84c405b5-bc29-4c6e-8620-4e283cd29fb2)
![Screenshot 2024-07-15 155440](https://github.com/user-attachments/assets/be1b01fd-3501-45dd-a5e3-71a5744d14c6)
![Screenshot 2024-07-15 155506](https://github.com/user-attachments/assets/51ea82da-13f7-417b-9de8-abb5d157ae8c)

**Comment by K-K-Kola** [comment]
Upon Further investigation here is what I found from basic debugging to help point us in the right direction.


![image_2024-07-15_160235655](https://github.com/user-attachments/assets/705a651f-c585-4e9b-b385-4f7fb196166b)

**Comment by tshegomotlatle** [comment]
Ignore the readme
